### PR TITLE
feat: bump golangci-lint to v1.55.2

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Problem:**
The golangci-lint version before v1.51.0 may have OOM issue with golang v1.20.

**Solution:**
Bump golangci-lint to a version after v1.51.0.

**Related Issue:**
https://github.com/harvester/harvester/issues/4938

### CODE REVIEW

**Review by ibrokethecloud — COMMENTED** [review]
should we setup linter to only warn about `dot-imports`? At present if we start changing dot-imports there will be a lot of work rebasing PR's since just about every integration test leveraging Ginkgo/Gomega is using the `dot-import`.

**Review by ibrokethecloud — COMMENTED** [review]
> should we setup linter to only warn about `dot-imports`? At present if we start changing dot-imports there will be a lot of work rebasing PR's since just about every integration test leveraging Ginkgo/Gomega is using the `dot-import`.  @bk201?

**Comment by ibrokethecloud** [comment]
dropping a `revive.toml` in project root, with the following allows us to skip checks: https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports

```more revive.toml
[rule.dot-imports]
  arguments = [{ allowedPackages = ["github.com/onsi/ginkgo/v2","github.com/onsi/gomega"] }]
```

**Comment by FrankYang0529** [comment]
> should we setup linter to only warn about `dot-imports`? At present if we start changing dot-imports there will be a lot of work rebasing PR's since just about every integration test leveraging Ginkgo/Gomega is using the `dot-import`.

I use another to solve `dot-imports`. May you take a look? Thank you.

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Review by bk201 — APPROVED** [review]

**Pull request merged**
