### PR TITLE
fix(usbdevice): close closed channel exception

### PR DESCRIPTION
**Pull request by Yu-Jack**
**Problem:**

Reproduce Steps

1. Plug in USB device A.
2. Unplug USB device A and plug it in again. This increases the device number.
3. Create a `usbdeviceclaim`.
4. Reboot the host.
5. Observe that the device number of USB device A is reset to the value from step 1.
6. Delete the `usbdeviceclaim`.
7. Observe the error from pcidevices-controller: close closed channel.

In this cause, the original `usbdeviceclaim` won't work due to device number changed. That's expected.

~~However, the `plugin.deregistered` channel is closed twice due to multiple calls to ListAndWatch. But, I cannot find the root cause yet.~~ Check https://github.com/harvester/pcidevices/pull/86#issuecomment-2275257248

https://github.com/user-attachments/assets/15f022ae-a313-498b-90eb-16a735cf1d59

**Solution:**

Do not use `close`, just make it buffered channel.

**Related Issue:**

https://github.com/harvester/harvester/issues/5762

**Test plan:**

Follow above steps, it shouldn't complain the same error.

https://github.com/user-attachments/assets/ab693cf2-b273-4031-a9a0-1e8462706152

### CODE REVIEW

**Review by ibrokethecloud — APPROVED** [review]

**Review by WebberHuang1118 — APPROVED** [review]
LGTM, thanks, do we need a separate issue for tracking the root cause?

**Comment by Yu-Jack** [comment]
@ibrokethecloud @WebberHuang1118 

I find the root cause, it's quite straightforward.

We're trying to open gRPC server, and close it after error happens. Each time we start the gRPC server, kubelete invokes `ListAndWatch` function.

But, the program is stuck here since it didn't receive any value from that two channels. 

```go
done := false
for !done {
	select {
	case <-plugin.update:
		if err := sendUpdate(plugin.devicesToKubeVirtDevicePlugin()); err != nil {
			return err
		}
	case <-plugin.stop:
		done = true
}
```

So, I'll add new channel which presents that the gRPC server is closed or not. Please check my latest commits to see the changes, thanks!

**Review by WebberHuang1118 — APPROVED** [review]
LGTM, thanks.

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Pull request merged**
